name: Deploy to Azure
on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: flying-game-server # Your Azure Web App name
  AZURE_WEBAPP_PACKAGE_PATH: "./server" # Set this to the path to your web app project
  NODE_VERSION: "20.x" # Set this to the node version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Debug Info
        run: |
          echo "App Name: ${{ env.AZURE_WEBAPP_NAME }}"
          echo "Node Version: ${{ env.NODE_VERSION }}"
          echo "Package Path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      - name: npm install and build
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        run: |
          npm install
          npm run build

      - name: Package for deployment
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        run: |
          mkdir deploy
          cp -r dist package.json package-lock.json web.config deploy/
          cd deploy
          # Create a server.js file to ensure Azure knows this is a Node.js app
          echo "require('./dist/index.js');" > server.js
          # Create a .env file with necessary settings
          echo "PORT=8080" > .env
          echo "DB_PATH=D:\\home\\site\\wwwroot\\db.sqlite" >> .env
          zip -r ../deploy.zip .
          cd ..
          echo "Deployment package contents:"
          unzip -l deploy.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Deploy to Azure WebApp"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREWEBAPP_PUBLISHPROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/deploy.zip

      - name: Logout from Azure
        run: |
          az logout
        if: always()
